// Full valid example matching experimentSchema (draft / snapshot shape).
// Used for engine testing, builder templates, and backend validation tests.
export const sampleStroop = {
  settings: {
    consentText: "You are participating in a study on attention. Your responses are anonymous. You may stop at any time.",
    fullscreen: true,
    showProgressBar: true,
    instructionsText: "Press F if the WORD matches its ink colour, J if it does not. Respond as fast as you can.",
    backgroundColor: "#ffffff",
    textColor: "#000000",
    fontSize: 48,
  },
  blocks: [
    {
      id: "block_practice",
      label: "Practice",
      shuffle: true,
      maxRepeats: 2,
      repetitions: 1,
      trials: [
        {
          id: "trial_p1",
          stimulus: { type: "text", content: "RED", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "f",
          condition: "congruent",
          feedback: { correct: "Correct!", incorrect: "Try again" },
        },
        {
          id: "trial_p2",
          stimulus: { type: "text", content: "BLUE", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "j",
          condition: "incongruent",
          feedback: { correct: "Correct!", incorrect: "Try again" },
        },
      ],
    },
    {
      id: "block_main",
      label: "Main",
      shuffle: true,
      maxRepeats: 2,
      repetitions: 1,
      trials: [
        {
          id: "trial_m1",
          stimulus: { type: "text", content: "GREEN", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "f",
          condition: "congruent",
          feedback: { correct: "Correct!", incorrect: "Wrong" },
        },
        {
          id: "trial_m2",
          stimulus: { type: "text", content: "RED", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "j",
          condition: "incongruent",
          feedback: { correct: "Correct!", incorrect: "Wrong" },
        },
        {
          id: "trial_m3",
          stimulus: { type: "text", content: "BLUE", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "f",
          condition: "congruent",
          itiMs: 300,
        },
        {
          id: "trial_m4",
          stimulus: { type: "text", content: "GREEN", url: null },
          duration: 2000,
          fixationDuration: 500,
          validKeys: ["f", "j"],
          correctKey: "j",
          condition: "incongruent",
          timeoutMs: 3000,
          itiMs: 300,
        },
      ],
    },
  ],
  branches: [
    {
      id: "branch_retry",
      from: "block_practice",
      to: "block_practice",
      condition: { metric: "accuracy", operator: "<", value: 0.7 },
    },
  ],
  loops: [],
};
